[[runners]]
name = "Check"
command = "cargo"
args = ["check"]
error_parser = "Rust"

[[runners]]
name = "Build --release"
command = "cargo"
args = ["build", "--release"]
error_parser = "Rust"

[[runners]]
name = "Run"
command = "cargo"
args = ["run"]

[[runners]]
name = "Run New Instance"
command = "./run_limited.sh"

[[runners]]
name = "Test"
command = "cargo"
args = ["test"]
error_parser = "Rust"

[[runners]]
name = "Clean"
command = "cargo"
args = ["clean"]

[[runners]]
name = "Format"
command = "cargo"
args = ["fmt", "--all"]

[[runners]]
name = "check.sh"
command = "./check.sh"

