#!/usr/bin/env bash
set -e

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -q /usr/share/icons/hicolor >/dev/null 2>&1 || true
fi

if command -v fc-cache >/dev/null 2>&1; then
    fc-cache -f /usr/share/fonts/truetype/polycredo-nerd >/dev/null 2>&1 || true
fi

exit 0
